### ISSUE TITLE
Modules: Order of lessons?

### ISSUE THREAD

**Issue by mitthrawnuruodo** [Fermain/-mollify#128]
Are the order of lessons correct? Or just random/alphabetic? Shouldn't they be in (recommended) reading/teaching order?

**Comment by Fermain** [comment]
Order of lessons/modules/courses is defined in the meta data section for each page:

```yaml
title: Example Lesson
tags:
  - Example
type: Lesson
previous: Introduction to Examples
```

By setting `previous` it will arrange the content in the correct order.
