### ISSUE TITLE
Re-render TTS file on Action

### ISSUE THREAD

**Issue by pretzL** [Fermain/-mollify#60]
Set up a GitHub action, or a set of actions, which re-render TTS files whenever the markdown content has been changed.

To do this, we would need to create a github action. That would need to be its own repo, i.e. `@mollify/tts` so that you can use it in a workflow as a step:

```yml
steps:
      - name: Render TTS
        uses: @mollify/tts
        with:
          match: '+page.md'
          voices: 
          - Bob
          - Susan
```
